clists/urls.py
from django.urls import path
from clists import views as cvs 

app_name = 'clists'

urlpatterns = [
	path('create/', cvs.create, name='create'),
	path('items/<int:id>/', cvs.items_data_add, name='items_add'),
	path('items_edit/<int:id>/', cvs.items_data_edit, name='items_edit'),
	path('items_del/<int:id>/', cvs.items_data_del, name='items_del'),
	path('title/',cvs.add_title, name='add_title'),
	path('myclists/', cvs.MyClists.as_view(), name='myclists'),
	path('clistview/<int:pk>/',cvs.ClistsView.as_view(), name='clistview'),
	path('clist_delete/<int:id>/', cvs.clists_delete_view, name='clist_del'),
]

tlist/urls.py
from django.contrib import admin
from django.urls import path, include
from clists import views as cv
from users import views as uv
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', cv.clist_landing_page, name='land_page'),
    path('clists/', include('clists.urls')),
    # Adding the urls for the allauth social login
    path('accounts/',include('allauth.urls')),
    # Adding the login and signup for the site with site credentials storage 
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('signup/',uv.SignUpView.as_view(), name='signup'),
]

clists/models.py
from django.db import models
from django.shortcuts import reverse
from users.models import TUser

# Create your models here.

STATUS_CHOICES = (
	('I','In Progress'),
	('C','Completed'),
	)


class CheckList(models.Model):
	title = models.CharField(max_length=255)
	date = models.DateTimeField(auto_now_add=True)
	user = models.ForeignKey(TUser, on_delete=models.CASCADE)


	def __str__(self):
		return self.title

	def get_absolute_url(self):
		return reverse('clists:clistview',args=(self.id,))

	# def date_info(self):
	# 	return self.date.date()


class Items(models.Model):
	items = models.CharField(max_length=255)
	# status = models.CharField(max_length=1, choices=STATUS_CHOICES)
	status = models.BooleanField(default=False)
	title = models.ForeignKey(CheckList, on_delete=models.CASCADE)

	class Meta:
		unique_together = ('items','title')


	def __str__(self):
		return f'{self.title}-{self.items}'

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager

# Create your models here.



class TUser(AbstractUser):
	username = None
	signup_date = models.DateTimeField(auto_now_add=True)

	email = models.EmailField(unique=True)

	USERNAME_FIELD = 'email'
	REQUIRED_FIELDS = []

	objects = CustomUserManager()


	def __str__(self):
		return self.email

clists/forms.py
from clists.models import Items, CheckList, STATUS_CHOICES
from django import forms

class CheckListForm(forms.ModelForm):

	title = forms.CharField(label='', widget=forms.TextInput(attrs={'class':'form-control title_ip', 'placeholder':"What's the title.?"}))

	class Meta:
		model = CheckList
		fields = ['title']


class ItemsForm(forms.ModelForm):

	items = forms.CharField(widget=forms.TextInput(attrs={'class':'form-control item-ip','placeholder':'Enter checklist items'}))
	# status = forms.ChoiceField(choices=STATUS_CHOICES, widget=forms.Select(attrs={'class':'form-control'}))
	status = forms.BooleanField(widget=forms.CheckboxInput(attrs={'class':'custom-control-input','id':'customSwitch1'}), required=False)
	class Meta:
		model = Items
		fields = ['items', 'status']

users/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms
from .models import TUser

class SignUpForm(UserCreationForm):

	email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':'Email'}))
	password1 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Enter Password'}))
	password2 = forms.CharField(label='', widget=forms.PasswordInput(attrs={'placeholder':'Re-Enter Password'}))
	class Meta:
		model = TUser
		# fields= ['email']
		fields = ['email','password1', 'password2']

clists/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.http import JsonResponse
from django.urls import reverse_lazy
from django.db import IntegrityError
from django.views.generic import ListView, DetailView
from django.views.generic.edit import DeleteView
# from django.conf.urls import HttpResponseRedirect
from django.contrib.auth.decorators import login_required

from clists.forms import CheckListForm, ItemsForm
from clists.models import Items, CheckList


# Adding title for the CheckList Template
@login_required
def add_title(request):
	print(request.user)
	if request.method == 'POST':
		tform = CheckListForm(request.POST)
		if tform.is_valid():
			tobj = tform.save(commit=False)
			tobj.user = request.user
			tobj.save()
			data = {
				'title':tobj.title,
				'id':tobj.id,
			}
			return JsonResponse(data)
		else:
			print(tform.errors)
	else:
		print('error')

# Ticklistt home page
def clist_landing_page(request):
	# cform = CheckListForm()
	# iform = ItemsForm()
	return render(request, 'clists/landing_page.htm')

# Checklist create view on the ticklistt web app
@login_required
def create(request):
	cform = CheckListForm()
	iform = ItemsForm()
	return render(request, 'clists/create.html', locals())

@login_required
def items_data_add(request, id):
	try:
		ctitle = CheckList.objects.get(pk=id)
		items = Items.objects.filter(title=ctitle, items__iexact=request.POST['items'])
		# print(not(items))
	except: 
		ctitle = None

	if request.method == 'POST' and ctitle and not(items):
		iform = ItemsForm(request.POST)
		if iform.is_valid():
			try:
				iobj = iform.save(commit=False)
				iobj.title = ctitle
				iobj.save()
				data = {
					'status': iobj.status,
					'items': iobj.items,
					'id':iobj.id,
				}

				return JsonResponse(data)

			# This will not run any more as we have added the items object in the if condition
			except IntegrityError as e:
				# print('running exception')
				# response = JsonResponse({'error':'Integrity Error DataExists'})
				# response.status_code = 409
				return JsonResponse({'status':'false','error':'Integrity Error DataExists'}, status=409)

	# 	Need to handle the form errors
	# 	else:
	# 		print(iform.errors)

	# Handling the no object (items) error
	else:
		# response = JsonResponse({'exists':'Entry Exists already'})
		# response.status_code = 500
		# print('issue..')
		# return JsonResponse(data)
		return JsonResponse({'exists':'Entry Exists already'}, status=409) 


# Edit existing items model object
@login_required
def items_data_edit(request, id):
	try:
		itm_obj = Items.objects.get(pk=id)
	except:
		itm_obj = None

	if request.method == 'POST' and itm_obj:
		ieform = ItemsForm(request.POST, instance=itm_obj)
		if ieform.is_valid():
			obj = ieform.save()
			# print(obj)
			data = { 
				'success':'success'
			}
			return JsonResponse(data)

		# Handle the form errors
		else:
			print(ieform.errors)

	#Handle the No object error itm_obj
	else:
		pass 

@login_required
def items_data_del(request, id):
	try:
		items = Items.objects.get(pk=id)
	except:
		items = None
	if request.method == 'DELETE' and items:
		items.delete()
		data = {
			'success':'removed'
		}
		return JsonResponse(data)



# Listview of the list of CheckList items created by user
class MyClists(ListView):
	model = CheckList
	template_name = 'clists/myclists.html'


# CheckList Template and it's Items DetailView
class ClistsView(DetailView):
	model = CheckList
	template_name = 'clists/clistsview.html'


# class ClistsDeleteView(DeleteView):
# 	model = CheckList
# 	success_url = reverse_lazy('myclists')

@login_required
def clists_delete_view(request, id):
	try:
		# print('hello')
		cl = CheckList.objects.get(pk=id)
		# print(cl, 'hello')
	except:
		cl = None 

	if request.method == 'DELETE' and cl:
		cl.delete()
		data = {'count':CheckList.objects.count()}

		return JsonResponse(data)

users/views.py
from django.shortcuts import render
# from django.contrib.auth.forms import UserCreationForm
from django.views.generic.edit import CreateView 
from django.urls import reverse_lazy
from .forms import SignUpForm

from .models import TUser


class SignUpView(CreateView):
	model = TUser
	form_class = SignUpForm
	template_name = 'users/signup.html'
	success_url = reverse_lazy('login')

	def form_valid(self, form):
		return super().form_valid(form)

clists/templates/clists/clistsview.html
{% extends 'clists/landing_page.htm' %}
{% block body_content %}
<div class="container col-md-7">
	<div class="shadow-lg">
		<div class=" p-3 alert-success">
			<span class="sp-title-cls" id={{object.id}}>{{object.title}}</span>
		</div>
		<div class="col-md-12 p-3 itms-secdv">
			{% for items in object.items_set.all %}
			<div class="form_container d-flex flex-row mt-2" id={{items.id}}>
				<form class="iform-cls form-inline">
				{% if items.status == True %}
				<div class="p-2 compl">
					<div id="Squarecheck">
						<span class="sq_check">
							<svg class="bi bi-check-square-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
					 		 <path fill-rule="evenodd" d="M2 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H2zm10.03 4.97a.75.75 0 0 0-1.08.022L7.477 9.417 5.384 7.323a.75.75 0 0 0-1.06 1.06L6.97 11.03a.75.75 0 0 0 1.079-.02l3.992-4.99a.75.75 0 0 0-.01-1.05z"/>	
							</svg>
						</span>
					</div>
				</div>
				<div class="form-group itm_ip_dv ml-3">
					<span class="item-ip">{{items.items}}<span>
				</div>	
				<div class="form-group custom-control custom-switch ml-3">
					<input type="checkbox" name="status" class="custom-control-input" id="ip{{items.id}}" checked="checked">
					<label class="custom-control-label" for="ip{{items.id}}">Status</label>
				</div>
				{% else %}
				<div class="p-2 compl"></div>
				<div class="form-group itm_ip_dv ml-3">
					<span class="item-ip">{{items.items}}<span>
				</div>	
				<div class="form-group custom-control custom-switch ml-3">
					<input type="checkbox" name="status" class="custom-control-input" id="ip{{items.id}}" >
					<label class="custom-control-label" for="ip{{items.id}}">Status</label>
				</div>
				{% endif %}
				<div class="form-group adderdv ml-3">
					<span class="adder">
						<svg class="bi bi-plus-circle-fill" width="1em" height="0.8em" viewBox="0 0 16 16" fill="currentColor" xmlns="	http://www.w3.org/2000/svg">
					  	<path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4a.5.5 0 0 0-1 0v3.5H4a.5.5 0 0 0 0 1h3.5V12a.5.5 0 0 0 1 0V8.5H12a.5.5 0 0 0 0-1H8.5V4z"/>
						</svg>
					</span>
					<span class="remoer">
					<svg class="bi bi-x-circle-fill" width="1em" height="0.8em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
			  			<path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zm-4.146-3.146a.5.5 0 0 0-.708-.708L8 7.293 4.854 4.146a.5.5 0 1 0-.708.708L7.293 8l-3.147 3.146a.5.5 0 0 0 .708.708L8 8.707l3.146 3.147a.5.5 0 0 0 .708-.708L8.707 8l3.147-3.146z"/>
					</svg>
					</span>
				</div>
				</form>
			</div>
			{% endfor %}
		</div>
	</div>
	
</div>
{% endblock body_content %}

clists/templates/clists/create.html
{% extends 'clists/landing_page.htm' %}
{% load crispy_forms_tags %}

<!-- Body content -->
{% block body_content %}
<div class="col-md-8 mx-auto" id='tldv'>
	<div class="col-md-10">
		<form class="tform-cls">
			{% csrf_token %}
			<!-- {% load crispy_forms_tags %} -->
			<div class="form-row p-2">
				{{cform}}	
				<hr>
			</div>
		</form>	
		<div class="itms-secdv">
			<div class="form_container d-flex flex-row mt-2" id='itm_cont'>
				<div class="p-2 compl"></div>
				<form class="iform-cls form-inline">
					{% csrf_token %}
					<div class="form-group itm_ip_dv p-2">
						{{iform.items}}
					</div>	
					<div class="form-group custom-control custom-switch ml-3">
						{{iform.status}}
						<label class="custom-control-label" for="customSwitch1">Status</label>
					</div>
				
					<div class="form-group ml-3 adderdv">
						<span class="adder">
						<svg class="bi bi-plus-circle-fill" width="0.7em" height="0.7em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
						  <path fill-rule="evenodd" d="M16 8A8 8 0 1 1 0 8a8 8 0 0 1 16 0zM8.5 4a.5.5 0 0 0-1 0v3.5H4a.5.5 0 0 0 0 1h3.5V12a.5.5 0 0 0 1 0V8.5H12a.5.5 0 0 0 0-1H8.5V4z"/>
						</svg>
						</span>
					</div>
				</form>	
			</div>
		</div>
	</div>
</div>
{% endblock body_content %}

clists/templates/clists/landing_page.htm
{% load static %}
{% load socialaccount %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
<head>
	<title>Ticklistt</title>
	<meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
	<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
	<!-- <link rel="stylesheet" type="text/css" href="{% static 'static/css/main.css' %}"> -->
	<link rel="stylesheet" type="text/css" href="{% static 'css/main.css' %}">
	<link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
	<link href='https://fonts.googleapis.com/css?family=Courgette' rel='stylesheet'>
  <!-- <link rel="stylesheet" href="/resources/demos/style.css"> -->




</head>
<body>
<!-- 	<div id="dialog-confirm" title="Are you sure?">
  <p><span class="ui-icon ui-icon-alert" style="float:left; margin:12px 12px 20px 0;"></span>These checklist will be permanently deleted. </p>
</div> -->
<!-- <div class="modal-dialog "> -->
	<!-- data-backdrop="static" -->

<!-- </div> -->
<div class="modal fade" id="sBdrop"  data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
<!-- 	      <div class="modal-header">
	        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div> -->
	      <div class="modal-body">
	      	<div class="wlc-txt titdiv-sgnp">
	      		<span class="ttitle">Ticklistt</span>
	      		<span>You are almost there to create your favorite checklist</span>
	      	</div>

	        <div id="my-signin2" class="md-dv">
	        	<!-- <a href="{% provider_login_url 'google' %}"><img class="g-img" src="{% static 'static/img/btn_google_signin_light_focus_web@2x.png' %}"></a> -->
	        	<a class='g-b-ig' href="{% provider_login_url 'google' %}"><img class="g-img" src="{% static 'img/btn_google_signin_light_focus_web.png' %}"></a>
	        </div>
	       	<div class="wlc-txt">
	      		<span class="mb-2 small">(or)</span>
	      	</div>
	       	<div id="my-signin2" class="md-dv">
	        	<!-- <a href="{% provider_login_url 'google' %}"><img class="g-img" src="{% static 'static/img/btn_google_signin_light_focus_web@2x.png' %}"></a> -->
	        	<a class='btn btn-secondary g-b-ig' href="{% url 'login' %}">Login with Ticklistt</a>
	        </div>
	      </div>
<!-- 	      <div class="modal-footer">
	        <button id='mod-can' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
	        <button id='mod-del' type="button" class="btn btn-sm btn-danger">Delete</button>
	      </div> -->
	    </div>
	</div>
</div>

	<!-- Title bar -->
	<div class="nav_bar_clists">
		{% block navibar %}
		<nav class="navbar navbar-expand-lg navbar-light bg-light">
			<a class="navbar-brand ttitle" href="{% url 'land_page' %}">Ticklistt</a>
			<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				{% if user.is_authenticated %}
			    <ul class="navbar-nav mr-auto">
			      <li class="nav-item">
			        <a class="nav-link create-cls" href="{% url 'clists:create' %}">Create</a>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link" href="{% url 'clists:myclists' %}">MyChecklists</a>
			      </li>
			    </ul>
			    {% endif %}
			    <ul class="navbar-nav ml-auto">
				{% if user.is_authenticated %}
					<li class="nav-item">
						<button class="nav-link btn btn-sm">{{user.email}}</button>
					</li>
					<li class="nav-item">
						<form method="post" action="{% url 'account_logout' %}">
							{% csrf_token %}
							<!-- {% if redirect_field_value %}
							<input type="hidden" name="{{redirect_field_name}}" value="{{redirect_field_value}}">
							{% endif %} -->
							<button type="submit" class="nav-link btn btn-sm sgp">SignOut</button>
						</form>
					</li>
				{% else %}
			      <li class="nav-item">
			        <button class="nav-link btn btn-sm lgn">Login</button>
			      </li>
			      <li class="nav-item">
			        <a class="nav-link btn btn-sm sgp" href="{% url 'signup' %}">SignUp</a>
			      </li>
				{% endif %}
				</ul>
			</div>
		</nav>
		{% endblock navibar %}
		
	</div>
	<!-- Main section of the web page -->
	<div class="mn_sec">
		{% block body_content %}
		<div class="col-md-8 mx-auto">
			<div class="container alert-success">
				<div class="strt-msg">
					<span class="hdline pr-1">Start creating the ticklistt as per your need to track the items and their progress..!! </span><a class="hdline btn btn-sm btn-secondary" href="{% url 'clists:create' %}">Create</a>
				</div>
			</div> 
			<div class="shadow-lg border rounded">
				<!-- <img src="{% static 'static/img/front_cover.JPG' %}"> -->
				<img src="{% static 'img/front_cover.JPG' %}">
			</div>
		</div>
		{% endblock body_content %}
	</div>
	<!-- Bottom section of the web page -->
	<div>
		
	</div>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<!-- JS, Popper.js, and jQuery -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>

<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
<!-- <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script> -->

<script src="https://apis.google.com/js/platform.js?onload=renderButton" async defer></script>
<!-- <script type="text/javascript" src="{% static 'static/js/clts_js_tmp.js'%}"></script> -->
<script type="text/javascript" src="{% static 'js/clts_js_tmp.js'%}"></script>
<!-- <script>
    // function onSuccess(googleUser) {
    //   console.log('Logged in as: ' + googleUser.getBasicProfile().getName());
    // }
    // function onFailure(error) {
    //   console.log(error);
    // }
    function renderButton() {
      gapi.signin2.render('my-signin2', {
        'scope': 'profile email',
        'width': 240,
        'height': 50,
        'longtitle': true,
        'theme': 'dark',
        // 'onsuccess': onSuccess,
        // 'onfailure': onFailure
      });
    }
  </script> -->
</body>
</html>

clists/templates/clists/myclists.html
{% extends 'clists/landing_page.htm' %}
{% load crispy_forms_tags %}
{% block body_content %}
<div class="modal fade" id="staticBackdrop"  data-keyboard="false" tabindex="-1" role="dialog" aria-labelledby="staticBackdropLabel" aria-hidden="true">
	<div class="modal-dialog modal-dialog-centered">
	    <div class="modal-content">
<!-- 	      <div class="modal-header">
	        <h5 class="modal-title" id="staticBackdropLabel">Modal title</h5>
	        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
	          <span aria-hidden="true">&times;</span>
	        </button>
	      </div> -->
	      <div class="modal-body">
	        <span>Are you sure you want to delete..? </span>
	      </div>
	      <div class="modal-footer">
	        <button id='mod-can' type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Cancel</button>
	        <button id='mod-del' type="button" class="btn btn-sm btn-danger">Delete</button>
	      </div>
	    </div>
	</div>
</div>
<div class="container col-md-6">
	<div class="p-3 d-flex justify-content-center alert-success">
		<span class="hdr-br">Your Templates (<span class="hdr-br" id="hdr-br-tmpl">{{object_list.count}}</span>)</span>
	</div>
	<div class="shadow-lg border">
		<ul class="list-group">
<!-- 			<li class="list-group-item lihd-cls">
				<div class="row">
					<div class="col-sm-6">
							<span class="ml-3">Template Name</span>
					</div>
					<div class="col-sm-6">
							<span>Created Date</span>
					</div>
				</div>
			</li> -->
			{% for item in object_list %}
			<li class="list-group-item li-class" id={{item.id}}>
				<div class="row">
					<div class="col-sm-4">
							<a class="ml-5" href="{{item.get_absolute_url}}">{{item.title}}</a>
					</div>
					<div class="col-sm-4">
							<span class="small">{{item.date.date}}</span>
					</div>
					<div class="col-sm-4">
						<span class="small del">
							<a class="clist-del-a" href="{% url 'clists:clist_del' item.id %}">
							<svg class="bi bi-trash-fill" width="1em" height="1em" viewBox="0 0 16 16" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
							  <path fill-rule="evenodd" d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5a.5.5 0 0 0-1 0v7a.5.5 0 0 0 1 0v-7z"/>
							</svg>
							</a>
						</span>
					</div>
				</div>
			</li>

			{% endfor %}
		</ul>
	</div>	
</div>

{% endblock %}

users/templates/users/login.html
{% extends 'clists/landing_page.htm' %}
<!-- {% load crispy_forms_tags %} -->
{% block navibar %}
{% endblock navibar %}
{% block body_content %}
<div class="container">
	<div class="col-md-6 shadow-lg p-3 mx-auto">
		<div class="titdiv-sgnp">
			<span class="ttitle">Ticklistt</span>
			<!-- <span class="">Enter the below details to Register your account</span> -->
		</div>
		<form method="post">
			{% csrf_token %}
			{{form|crispy}}
			<div class="sgnpbtn">
			 	<input class="btn btn-secondary" type="submit" name="submit" value="Login">
			 	<a class="lgn ml-2" href="#">Forgot your password..?</a>
			 </div>
		</form>
		<div class="lg-ft mt-3 p-2">
			<div class="lgn-btm wlc-txt">
				<span class="small p-1">Don't have an account</span><a class="small" href="{% url 'signup' %}">SignUp</a>
			</div>
			<div class="wlc-txt">
		      		<span class="mb-2 small">(or)</span>
		    </div>
			<div class="lgn-btm wlc-txt">
				<a href='' class="small lgn">Sign with different options</a>
			</div>
		</div>
	</div>
</div>
{% endblock body_content %}

users/templates/users/signup.html
{% extends 'clists/landing_page.htm' %}
{% load crispy_forms_tags %}
{% block navibar%}
{% endblock navibar %}
{% block body_content %}
<div class="container">
	<div class="col-md-5 shadow-lg mx-auto p-3">
		<div class="titdiv-sgnp">
			<span class="ttitle">Ticklistt</span>
			<span class="small text-dark">Enter the below details to Register your account</span>
		</div>
		<form method="post" class="p-2">
			 {% csrf_token %}
			 {{form|crispy}}
			 <div class="sgnpbtn">
			 	<input class="btn btn-success" type="submit" name="submit" value="SignUp">
			 	<span class="ml-2 small">Already have an account..? </span><a class="lgn small" href="#">Login</a>
			 </div>
		</form>
	</div>
	
</div>
{% endblock body_content %}